name: Push to Docker Hub
on:
  workflow_run:
    workflows:
      - "Flask application testing Workflow"
    types:
      - completed

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
