name: Push to Docker Hub
on:
  workflow_run:
    workflows:
      - "Flask application testing Workflow"
    types:
      - completed

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Pull Docker image
        run: |
          docker pull qaiser45/qaiser-images:Flask-Github-Aggregator

      - name: Tag Docker image for Docker Hub
        run: |
          docker tag qaiser45/qaiser-images:Flask-Github-Aggregator ${{ secrets.DOCKER_USERNAME }}/flask-github-aggregator:latest

      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/flask-github-aggregator:latest
