name: Flask application testing Workflow

on:
    pull_request:
        branches:
            - main

jobs:
    test:
        runs-on: ubuntu_latest
        defaults:
            run:
                working-directory: .
                
        strategy:
            matrix:
                python-version: [3.11]

        env:
            DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
            TOKEN: ${{ secrets.TOKEN }}

        steps:
            - uses: actions/checkout@v3

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                python-version: ${{ matrix.python-version }}

            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt
        

